name: srrl
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytest
  - pip
  - setuptools=65.5.0
  - pip:
    - gymnasium~=0.29.1
    - pygame~=2.1
    - imageio==2.25.0
    - moviepy==1.0.3
    - rich==13.4.2
    - wandb==0.13.11 
    - rliable==1.0.8
    - numba>=0.56
    - pycairo~=1.21
    - Shapely~=1.8.4
    - tensorboard
    - tqdm==4.65.0
    - hydra-core==1.3.2
    - "jax[cuda12]==0.4.24"
    - flax==0.8.1
    - optax==0.1.9
    - distrax==0.1.5
    - -e ./envs/CarEnv
